//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection_Logs
    {
        public int Log_id { get; set; }
        public int Request_id { get; set; }
        public int Employee_id { get; set; }
        public Nullable<System.DateTime> Collection_date { get; set; }
        public Nullable<System.DateTime> Distribution_date { get; set; }
        public byte[] Distribution_status { get; set; }
    
        public virtual Collection_requests Collection_requests { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
